export const CONFIG = {
	grid: { primary: 10, fallback: 5 },
	segment: { short: 80, long: 250 },
	spacing: { minComponentGap: 12, wireToPin: 10, wireToBody: 12 },
	body: { shrink: 2, overlapShrink: 5 },
	activeArea: {
		maxWidth: 1520,
		maxHeight: 920,
		maxAreaPerPart: 38000,
	},
	text: {
		allowFloating: false,
		allowedPatterns: [],
	},
	netflag: { halfSize: 8 },
	label: {
		textWidthPerChar: 6,
		textWidthPadding: 16,
		minTextWidth: 38,
		icClearanceSlack: 2,
		minFlagGap: 8,
		minSignalLabelGap: 1,
		connectorClearance: 55,
	},
	noConnect: { halfSize: 5, clearance: 1 },
	align: { tolerance: 15, minCluster: 2 },
	wiring: {
		detourRatio: 1.3,
		maxLocalBends: 1,
		collinearEps: 0.6,
		continuousSignalNets: [
			'USB_CC1', 'USB_CC2',
			'PMOS_GATE', 'PGATE_PULL', 'Q2_GATE',
			'RLY1_GATE', 'RLY2_GATE',
			'RLY1_COIL_A', 'RLY1_COIL_V', 'RLY2_COIL_A', 'RLY2_COIL_V',
		],
	},
	module: {
		boxMargin: 24,
		minGap: 40,
		wireBoxShrink: 8,
		interlockMargin: 0,
		interlockMaxSeparation: 180,
		interlockPartialMin: 0.2,
		interlockPartialMax: 0.75,
	},
	reference: {
		moduleMargin: 12,
		minRepeatedModuleCorridor: 90,
		maxModuleArea: {
			pmos: 115000,
		},
		maxModuleAspect: {
			usb: 3.6,
			ldo: 3.0,
			btn1: 2.2,
			btn2: 2.2,
			pmos: 3.2,
			relay1: 2.4,
			relay2: 2.4,
		},
		maxSupportDistance: {
			btnToMcu: 320,
			ldoToMcu: 430,
		},
		maxInputColumnSkew: 140,
		minOutputColumnGap: 220,
		minTerminalEdgeGap: 80,
		minRepeatedVerticalCorridor: 90,
		minOutputSubcolumnGap: 250,
		maxOutputSubcolumnGap: 460,
		minModuleInternalPacking: {
			pmos: 0.07,
			relay1: 0.08,
			relay2: 0.08,
		},
	},
	usbSupport: {
		maxCcRowDelta: 1,
		minCcPinGap: 95,
		maxCcPinGap: 115,
		maxSeriesColumnSkew: 4,
		minSeriesRowPitch: 20,
		maxSeriesRowPitch: 45,
		maxSeriesRowDelta: 35,
		maxSeriesPinGap: 165,
	},
	pmosSupport: {
		maxClampRowDelta: 8,
		minClampColumnGap: 20,
		maxClampColumnGap: 55,
		maxGateSupportColumnSkew: 12,
		minGateSupportVerticalSpan: 90,
		maxGateSupportVerticalSpan: 190,
		maxGateSupportToQ1XGap: 90,
		minDriverBelowQ1: 95,
		maxDriverBelowQ1: 200,
		maxDriverColumnSkew: 35,
		maxR2Q2DirectXSkew: 1,
		maxR2Q2DirectYGap: 40,
		maxR3ToQ2GateGap: 75,
		maxR4GateRowDelta: 35,
		maxR4ToQ2GateXGap: 45,
	},
	relaySupport: {
		minTerminalRightOfMos: 105,
		maxTerminalRightOfMos: 190,
		maxTerminalRowDelta: 90,
		minDiodeRightOfMos: 35,
		maxDiodeRightOfMos: 90,
		minDiodeLeftOfTerminal: 45,
		maxDiodeLeftOfTerminal: 110,
		maxDiodeCoilRowDelta: 5,
		maxFlybackDirectRun: 90,
		minFlybackDirectRun: 45,
		maxFlybackBridgeDrop: 25,
		maxRsGateRowDelta: 5,
		minRsLeftOfMosGate: 35,
		maxRsLeftOfMosGate: 75,
		minRpdBelowGate: 20,
		maxRpdBelowGate: 65,
		maxRpdGateXGap: 40,
	},
	ldoSupport: {
		minCapRightOfRegulator: 45,
		maxCapRightOfRegulator: 170,
		maxCapColumnSkew: 8,
		minCapPitch: 35,
		maxCapPitch: 70,
		maxVoutRowDelta: 35,
		maxPowerPinToBusDelta: 35,
		minGndBelowPowerPin: 25,
		maxGndBelowPowerPin: 55,
	},
	buttonSupport: {
		maxPullupXOffset: 35,
		minPullupAboveSwitch: 45,
		maxPullupAboveSwitch: 80,
		maxPullupSignalXGap: 8,
		minPullupSignalYGap: 10,
		maxPullupSignalYGap: 45,
		minResetCapRightOfSwitch: 65,
		maxResetCapRightOfSwitch: 125,
		maxResetCapRowDelta: 40,
		maxResetCapSignalRowDelta: 15,
		minResetCapGndRightOfSignal: 25,
		maxResetCapGndRightOfSignal: 55,
	},
	mcuInterface: {
		leftSignals: [
			{ pin: '2', net: 'RESET_EN' },
			{ pin: '3', net: 'EXT_PWR_EN' },
			{ pin: '4', net: 'RELAY1_EN' },
			{ pin: '5', net: 'RELAY2_EN' },
			{ pin: '8', net: 'BOOT_IO9' },
			{ pin: '13', net: 'USB_DN' },
			{ pin: '14', net: 'USB_DP' },
		],
		pinEscapeMin: 8,
		pinEscapeMax: 22,
		preferredPinEscapeLen: 20,
		preferredNamedStubLen: 40,
		maxEscapeColumnDelta: 4,
		maxLabelStubLeftOfMcu: 105,
		minNamedStubLen: 24,
		maxNamedStubLen: 55,
		maxLabelColumns: 1,
		labelColumnTolerance: 2,
		minLabelRowPitch: 10,
		maxLabelLaneYMargin: 80,
		maxInterfaceVerticalLen: 8,
		maxPinEscapeJogLen: 12,
	},
	libraryBinding: {
		expectedByRef: {
			D2: {
				names: ['1N4148W_C81598', '1N4148W'],
				Symbol: '703c18046c7d1ac8',
				Device: 'cb95f1734719a1ce',
				Footprint: '1fd32051a468dcc1',
			},
			D3: {
				names: ['1N4148W_C81598', '1N4148W'],
				Symbol: '703c18046c7d1ac8',
				Device: 'cb95f1734719a1ce',
				Footprint: '1fd32051a468dcc1',
			},
		},
	},
	structureGate: {
		minShortSegmentRatio: 0.88,
		shortSegmentMaxLen: 80,
		maxLongSegments: 4,
		longSegmentMinLen: 180,
		maxVeryLongSegments: 0,
		veryLongSegmentMinLen: 250,
		minModuleGap: 90,
		maxModuleWireIntrusions: 0,
	},
	rawWire: {
		maxPrimitiveSegments: 16,
		maxPairSegments: 32,
		maxDuplicatePoints: 0,
		maxPairBranchPoints: null,
	},
	match: { snap: 0.5 },
	severity: { hard: 'hard', soft: 'soft', info: 'info' },
};
