// Generated by workflows/pack_scaffold.mjs when circuit packs are added.
// Keep imports static so generator and gates remain synchronous.
import { pack as aihwdebugger } from './aihwdebugger/pack.mjs';
import { pack as divider } from './divider/pack.mjs';

const PACKS = new Map([
	[aihwdebugger.id, aihwdebugger],
	[divider.id, divider],
]);

export function getCircuitPack(id = 'aihwdebugger') {
	const pack = PACKS.get(id || 'aihwdebugger');
	if (!pack) throw new Error(`Unknown circuit pack: ${id}`);
	return pack;
}

export function circuitPackIds() {
	return [...PACKS.keys()];
}
